-- 017_briefs.sql
--
-- Periodic briefs: what the agents are doing and where it is heading.
--
-- Deliberately not raw output. Watching a transcript scroll is not oversight —
-- it is the opposite, because the volume hides whether anything is actually
-- going anywhere. A brief answers: what is running, what changed since last
-- time, what is stuck, and what needs a decision.
--
-- Generated by a cheap model. Summarizing agent activity every half hour on a
-- frontier model would cost more than the work being summarized.

CREATE TABLE briefs (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    kind           text NOT NULL DEFAULT 'periodic'
                     CHECK (kind IN ('periodic', 'daily', 'mission', 'on_demand')),

    headline       text NOT NULL,
    body           text NOT NULL,

    -- Split out so the app and a push notification can lead with what matters
    -- rather than making the reader parse prose for it.
    needs_decision text,
    stuck          text,

    active_agents  int NOT NULL DEFAULT 0,
    active_missions int NOT NULL DEFAULT 0,
    cost_since_last numeric(12, 6) NOT NULL DEFAULT 0,

    covers_from    timestamptz,
    covers_to      timestamptz NOT NULL DEFAULT now(),
    model          text,

    -- Set once delivered, so a restart does not re-push a brief already seen.
    notified_at    timestamptz,
    created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX briefs_created_idx ON briefs (created_at DESC);
CREATE INDEX briefs_undelivered_idx ON briefs (created_at) WHERE notified_at IS NULL;

ALTER TABLE summaries DROP CONSTRAINT IF EXISTS summaries_scope_check;
ALTER TABLE summaries ADD CONSTRAINT summaries_scope_check
    CHECK (scope IN ('session', 'agent', 'turn_range', 'day', 'brief', 'mission'));
